services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: backuptool
      POSTGRES_USER: backup_user
      POSTGRES_PASSWORD: backup_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: